---
provisioner:
  name: chef_zero
  data_bags_path: <%= ENV['DATA_BAGS_PATH'] %>
  encrypted_data_bag_secret_key_path: <%= ENV['DATA_BAG_SECRET_PATH'] %>
  require_chef_omnibus: 12.13.37

driver:
  name: ec2
  security_group_ids:
    - sg-9ca1a7e6
  region: <%= ENV['AWS_REGION'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID']%>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE='] %>
  vpc_mode: true
  vpc: vpc-4251db24
  subnet_id: subnet-8d18e3c5
  associate_public_ip: true
  
platforms:
  - name: CentOS_69
    driver:
      image_id: ami-a7d82edf
      instance_type: t2.medium
      associate_public_ip: true
      iam_profile_name: main_infra
      block_device_mappings:
      - device_name: /dev/sda1
        ebs:
          volume_size: 8
          delete_on_termination: true
      tags:
        Name: maduro-mediawiki-tk
        Product: maduro.nfernal
        ChargeCode: thisiscostingmeafortune

transport:
  name: ssh
  connection_timeout: 15
  connection_retries: 30
  ssh_key: <%= ENV['AWS_SSH_KEY'] %>
  username: centos

verifier:
  name: inspec
  inspec_tests:
        - test/integration/default

suites:
  - name: mediawiki
    provisioner:
      named_run_list: mediawiki